### ISSUE TITLE
Unable to login to web dashboard: failed to initialize database

### ISSUE THREAD

**Issue by kitaguch** [SINDAN/sindan-docker#4]
- Environment
$ uname -a
Linux saturn 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ docker -v
Docker version 19.03.5, build 633a0ea838
$ docker-compose -v
docker-compose version 1.25.4, build 8d51620a

- Commands
$ git clone --recursive https://github.com/SINDAN/sindan-docker
$ cd sindan-docker
-- make secrets files --
$ make pull init
$ make run log
$ docker exec -it sindan-docker_mysql_1 bash
root@sindan-mysql:/# mysql -u sindan -p
mysql> use sindan_production;
mysql> select * from users;
Empty set (0.00 sec)

- Logs
[make_pull_init.txt](https://github.com/SINDAN/sindan-docker/files/4224647/make_pull_init.txt)
[make_run_log.txt](https://github.com/SINDAN/sindan-docker/files/4224652/make_run_log.txt)

**Comment by mi2428** [comment]
Case closed
